2024-08-10 20:09:09,392 INFO    MainThread:80597 [wandb_setup.py:_flush():76] Current SDK version is 0.17.6
2024-08-10 20:09:09,392 INFO    MainThread:80597 [wandb_setup.py:_flush():76] Configure stats pid to 80597
2024-08-10 20:09:09,392 INFO    MainThread:80597 [wandb_setup.py:_flush():76] Loading settings from /Users/gino/.config/wandb/settings
2024-08-10 20:09:09,392 INFO    MainThread:80597 [wandb_setup.py:_flush():76] Loading settings from /Users/gino/promisegat4/wandb/settings
2024-08-10 20:09:09,392 INFO    MainThread:80597 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-08-10 20:09:09,392 INFO    MainThread:80597 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-08-10 20:09:09,392 INFO    MainThread:80597 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-08-10 20:09:09,392 INFO    MainThread:80597 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-08-10 20:09:09,392 INFO    MainThread:80597 [wandb_init.py:_log_setup():521] Logging user logs to /Users/gino/promisegat4/wandb/run-20240810_200909-iezvb87u/logs/debug.log
2024-08-10 20:09:09,392 INFO    MainThread:80597 [wandb_init.py:_log_setup():522] Logging internal logs to /Users/gino/promisegat4/wandb/run-20240810_200909-iezvb87u/logs/debug-internal.log
2024-08-10 20:09:09,392 INFO    MainThread:80597 [wandb_init.py:init():559] calling init triggers
2024-08-10 20:09:09,393 INFO    MainThread:80597 [wandb_init.py:init():566] wandb.init called with sweep_config: {}
config: {}
2024-08-10 20:09:09,393 INFO    MainThread:80597 [wandb_init.py:init():609] starting backend
2024-08-10 20:09:09,393 INFO    MainThread:80597 [wandb_init.py:init():613] setting up manager
2024-08-10 20:09:09,393 INFO    MainThread:80597 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2024-08-10 20:09:09,394 INFO    MainThread:80597 [wandb_init.py:init():621] backend started and connected
2024-08-10 20:09:09,399 INFO    MainThread:80597 [wandb_run.py:_label_probe_notebook():1337] probe notebook
2024-08-10 20:09:09,400 INFO    MainThread:80597 [wandb_run.py:_label_probe_notebook():1347] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-08-10 20:09:09,400 INFO    MainThread:80597 [wandb_init.py:init():716] updated telemetry
2024-08-10 20:09:09,420 INFO    MainThread:80597 [wandb_init.py:init():749] communicating run to backend with 90.0 second timeout
2024-08-10 20:10:39,856 ERROR   MainThread:80597 [wandb_init.py:init():775] encountered error: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-08-10 20:10:39,859 ERROR   MainThread:80597 [wandb_init.py:init():1187] error in wandb.init()
Traceback (most recent call last):
  File "/Users/gino/promisegat4/venv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1177, in init
    return wi.init()
           ^^^^^^^^^
  File "/Users/gino/promisegat4/venv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 781, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-08-10 20:18:43,766 INFO    MainThread:80597 [wandb_settings.py:_apply_login():1936] Applying login settings: {}
2024-08-10 20:18:43,774 INFO    MainThread:80597 [wandb_setup.py:_flush():76] Current SDK version is 0.17.6
2024-08-10 20:18:43,774 INFO    MainThread:80597 [wandb_setup.py:_flush():76] Configure stats pid to 80597
2024-08-10 20:18:43,774 INFO    MainThread:80597 [wandb_setup.py:_flush():76] Loading settings from /Users/gino/.config/wandb/settings
2024-08-10 20:18:43,774 INFO    MainThread:80597 [wandb_setup.py:_flush():76] Loading settings from /Users/gino/promisegat4/wandb/settings
2024-08-10 20:18:43,774 INFO    MainThread:80597 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-08-10 20:18:43,774 INFO    MainThread:80597 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-08-10 20:18:43,774 INFO    MainThread:80597 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-08-10 20:18:43,774 INFO    MainThread:80597 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-08-10 20:18:43,774 INFO    MainThread:80597 [wandb_init.py:_log_setup():521] Logging user logs to /Users/gino/promisegat4/wandb/run-20240810_201843-4n9edfjm/logs/debug.log
2024-08-10 20:18:43,774 INFO    MainThread:80597 [wandb_init.py:_log_setup():522] Logging internal logs to /Users/gino/promisegat4/wandb/run-20240810_201843-4n9edfjm/logs/debug-internal.log
2024-08-10 20:18:43,774 INFO    MainThread:80597 [wandb_init.py:init():559] calling init triggers
2024-08-10 20:18:43,774 INFO    MainThread:80597 [wandb_init.py:init():566] wandb.init called with sweep_config: {}
config: {}
2024-08-10 20:18:43,774 INFO    MainThread:80597 [wandb_init.py:init():609] starting backend
2024-08-10 20:18:43,774 INFO    MainThread:80597 [wandb_init.py:init():613] setting up manager
2024-08-10 20:18:43,775 INFO    MainThread:80597 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2024-08-10 20:18:43,775 INFO    MainThread:80597 [wandb_init.py:init():621] backend started and connected
2024-08-10 20:18:43,795 INFO    MainThread:80597 [wandb_run.py:_label_probe_notebook():1337] probe notebook
2024-08-10 20:18:43,795 INFO    MainThread:80597 [wandb_run.py:_label_probe_notebook():1347] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-08-10 20:18:43,795 INFO    MainThread:80597 [wandb_init.py:init():716] updated telemetry
2024-08-10 20:18:43,823 INFO    MainThread:80597 [wandb_init.py:init():749] communicating run to backend with 90.0 second timeout
2024-08-10 20:20:14,263 ERROR   MainThread:80597 [wandb_init.py:init():775] encountered error: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-08-10 20:20:14,265 ERROR   MainThread:80597 [wandb_init.py:init():1187] error in wandb.init()
Traceback (most recent call last):
  File "/Users/gino/promisegat4/venv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1177, in init
    return wi.init()
           ^^^^^^^^^
  File "/Users/gino/promisegat4/venv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 781, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
